networks:
  litefox_network:
    driver: bridge

services:
  litefox-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - APP_DOMAIN=${LITEFOX_DOMAIN}
      - IS_PRODUCTION=${IS_PRODUCTION}
      - LITEFOX_DOMAIN=${LITEFOX_DOMAIN}
      - APP_WORKDIR=${APP_WORKDIR}
    volumes:
      - ./certbot/conf:/app/certbot/conf:ro
      - ./certbot/www:/app/certbot/www:ro
      - ./certbot/www/.well-known/acme-challenge:/app/www/certbot/.well-known/acme-challenge
    networks:
      - litefox_network
    restart: always

  certbot_init:
    profiles: [prod]
    image: certbot/certbot
    entrypoint: >
      /bin/sh -c "certbot certonly --webroot -w /var/www/certbot 
      -d ${LITEFOX_DOMAIN} -d www.${LITEFOX_DOMAIN} --email ${LITEFOX_EMAIL} 
      --agree-tos --no-eff-email --keep-until-expiring"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/www/.well-known/acme-challenge:/var/www/certbot/.well-known/acme-challenge
    networks:
      - litefox_network